### ISSUE TITLE
Small gap on right side of pages.

### ISSUE THREAD

**Issue by jwr12135** [Cornerstone-Church/CAG-MainWebsite#169] opened 2019-11-12 01:51 UTC
There is a small gap on the right side of the pages, "**About**, **Missions**, and **Give**" that you can scroll to. On the rest of the pages, if the screen width is between 800px and 835px the gap is created.

**Comment by silentsonata** [comment] 2019-11-27 14:05
Hmmm....Yea I have been seeing this pop up all over the site. Any idea what is causing it?

**Comment by steamwings** [comment] 2019-12-03 19:12
#182 contains a suggested fix, but it doesn't address the source of the gap.

**Comment by steamwings** [comment] 2019-12-03 19:31
Okay I looked around a bit and my hunch was right. That margin goes away if you put everything into one of the `<div class="content">`. For some reason `width:100%` (for instance in the `#banner-tuesday` ruleset in give_style.css) doesn't seem to be working as expected.

**Comment by silentsonata** [comment] 2019-12-06 14:23
@steamwings Thanks for looking into this! The commit has been pushed! 😄

**Comment by silentsonata** [comment] 2019-12-06 14:25
Let keep this open as it roles out. Once the problem can be confirmed as fixed I'll close it.

**Comment by steamwings** [comment] 2019-12-06 15:12
Looks like the hack worked for Give, but there's a (somewhat smaller) scrollable gap on About and Missions.

**Comment by silentsonata** [comment] 2019-12-08 13:03
Hmm....I am not seeing it. Maybe it takes a little bit to apply sitewide due to cache?

**Comment by silentsonata** [comment] 2020-01-02 13:25
@steamwings What browser and build are you seeing this in? Maybe I could download it and see if I can replicate it.

**Comment by silentsonata** [comment] 2020-02-04 14:12
This ticket has been open for a while with no progress or reports. If this issue appears again we can open this back up.

**Closed by silentsonata** 2020-02-04 14:12 UTC
Labels: bug
